
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**.cs'

env:
  PROJECT_NAME: UnityProject
  PROJECT_PATH: "UnityProject/"
  
jobs:
  inspection:
    runs-on: ubuntu-latest
    # Use gameCi container with installed Unity to keep editor dlls for linter
    container: unityci/editor:ubuntu-2022.3.24f1-linux-il2cpp-3

    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-lint-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-lint-

      - name: Generate Solution
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        run: unity-editor -batchmode -nographics -logFile /dev/stdout -projectPath ${{ env.PROJECT_PATH }} -executeMethod Packages.Rider.Editor.RiderScriptEditor.SyncSolution -username "$UNITY_EMAIL" -password "$UNITY_PASSWORD" -serial "$UNITY_SERIAL" -quit
      
      - name: Return License
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        if: always()
        run: unity-editor -logFile /dev/stdout -username "$UNITY_EMAIL" -password "$UNITY_PASSWORD" -quit -returnlicense

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      # Inspect code instalation could not add itself to path. Doing it before manually.
      - run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      # dotnet tool update --global JetBrains.ReSharper.GlobalTools fails to run if pwd contains several projetcs
      - run: mkdir UnityProjectIsolated; mv  -v ${{ env.PROJECT_PATH }}/* UnityProjectIsolated/

      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: UnityProjectIsolated/${{ env.PROJECT_NAME }}.sln
          solutionWideAnalysis: false
          minimumReportSeverity: warning
          minimumSeverity: warning
          include: |
            **.cs