
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**.cs'

env:
  PROJECT_NAME: UnityProject
  PROJECT_PATH: "UnityProject/"
  TARGET_PLATFORM: "Android"
  
jobs:
  inspection:
    runs-on: ubuntu-latest
    # Use gameCi container with installed Unity to keep editor dlls for linter
    container: unityci/editor:ubuntu-2022.3.24f1-linux-il2cpp-3

    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-lint-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-lint-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}  # Unity professional
          #UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }} # Unity personal
        with:
          targetPlatform: ${{ env.TARGET_PLATFORM }}
          projectPath: ${{ env.PROJECT_PATH }}
          buildMethod: Packages.Rider.Editor.RiderScriptEditor.SyncSolution
          #unityLicensingServer: [url to your license server]
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      # dotnet tool update fails to run if pwd contains several projetcs
      - run: mkdir UnityProjectIsolated; mv  -v ${{ env.PROJECT_PATH }}/* UnityProjectIsolated/
     
      # Inspect code instalation could not add itself to path. Doing it before manually.
      - run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH    
      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: UnityProjectIsolated/${{ env.PROJECT_NAME }}.sln
          solutionWideAnalysis: false
          minimumReportSeverity: warning
          minimumSeverity: warning
          include: |
            **.cs